app/availability/__init__.py
from flask import Blueprint

bp = Blueprint('availability', __name__)

from app.availability import routes

app/availability/routes.py
"""
    app.availability.routes
    ===============
    Routes used for checking availability
"""

from flask_login import login_required
from app.models import User, Checkin, Location
from app.availability import bp
from flask import render_template


@bp.route('/availability/user_list', methods=['GET'])
@login_required
def user_list():
    """Overview of all registered users"""
    users = User.query.order_by(User.name).all()
    return render_template(
        'availability/user_list.html', title='User list', users=users)


@bp.route('/availability/user/<user_id>', methods=['GET'])
@login_required
def user_availability(user_id):
    """Availability and location overview of a selected user"""
    user = User.query.filter_by(id=user_id).first()
    checkins = Checkin.query.filter_by(user_id=user_id)
    checkin = checkins[-1]
    location = Location.query.filter_by(id=checkin.location_id).first()
    availability = checkin.availability
    if availability:
        availability="Available"
    else:
        availability="Not available"
    return render_template(
        'availability/user_availability.html', user=user,
        location=location, availability=availability, title='Availability'
    )


@bp.route('/availability/location_list', methods=['GET'])
@login_required
def location_list():
    """Overview of all registered locations"""
    locations = Location.query.order_by(Location.name).all()
    return render_template(
        'availability/location_list.html', title='Location list',
        locations=locations)


@bp.route('/availability/location/<location_id>', methods=['GET'])
@login_required
def location_availability(location_id):
    """Availability overview of a specific location"""
    location = Location.query.filter_by(id=location_id).first()
    present = []

    for user in User.query.all():
        last_checkin = user.checkins.all()[-1]
        if last_checkin in location.checkins.all():
            present.append(last_checkin)
    present_nr = len(present)

    return render_template(
        'availability/location_availability.html', location=location,
        present_nr=present_nr, present=present, title='Availability')

app/templates/availability/location_availability.html
{% extends "base.html" %}

{% block app_content %}
{% if current_user.role == 'admin' %}
  <meta http-equiv="refresh" content="5">
{% endif %}
<div id="location">
  <ul>
    <li><strong>{{ 'Name' }}:</strong> {{ location.name }}</li>
    <li><strong>{{ 'Building' }}:</strong> {{ location.building }}</li>
    <li><strong>{{ 'Current number of people present' }}:</strong> {{ present_nr }}</li>
  </ul>
  <h2>Currently present</h2>
      <table id="users" class="table table-striped">
        <tr id="header-row">
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Availability</th>
            <th>Time</th>
            <th></th>
        </tr>
        {% for checkin in present %}
            <tr id="row">
                <td>{{ checkin.User.id }}</td>
                <td>{{ checkin.User.name }}</td>
                <td>{{ checkin.User.email }}</td>
                {% if checkin.availability == True %}
                  <td>Available</td>
                {% else %}
                  <td>Not Available</td>
                {% endif %}
                <td>{{ checkin.time }}</td>
                <td><a href="{{ url_for('availability.user_availability', user_id=checkin.User.id) }}">{{ 'Details' }}</a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/availability/location_list.html
{% extends "base.html" %}

{% block app_content %}
<div id="overview">
    <table id="locations" class="table table-striped">
        <tr id="header-row">
            <th>ID</th>
            <th>{{ 'Name' }}</th>
            <th>{{ 'Building' }}</th>
            <th></th>
        </tr>
        {% for location in locations %}
            <tr id="row">
                <td>{{ location.id }}</td>
                <td>{{ location.name }}</td>
                <td>{{ location.building }}</td>
                <td><a href="{{ url_for('availability.location_availability', location_id=location.id) }}">{{ 'Details' }}</a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

app/templates/availability/user_availability.html
{% extends "base.html" %}

{% block app_content %}
<div id="user">
  <ul>
    <li><strong>{{ 'Name' }}:</strong> {{ user.name }}</li>
    <li><strong>{{ 'Email' }}:</strong> {{ user.email }}</li>
    <li><strong>{{ 'Role' }}:</strong> {{ user.role }}</li>
  </ul>
    <h3><strong>{{ 'Location' }}:</strong> {{ location.name }}</h3>
    <h3><strong>{{ 'Availability' }}:</strong> {{ availability }}</h3>
</div>
{% endblock %}

app/templates/availability/user_list.html
{% extends "base.html" %}

{% block app_content %}
<div id="overview">
    <table id="users" class="table table-striped">
        <tr id="header-row">
            <th>ID</th>
            <th>{{ 'Name' }}</th>
            <th>{{ 'Email' }}</th>
            <th></th>
        </tr>
        {% for user in users %}
            <tr id="row">
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.email }}</td>
                <td><a href="{{ url_for('availability.user_availability', user_id=user.id) }}">{{ 'Details' }}</a></td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}